package com.example.ktbook802.model

import com.google.gson.annotations.SerializedName

data class Book(
    // 매핑해서 값을 가져오기 위해 @SerializedName
    // 파라미터 자리에 있는 것은 JSON의 값이다.(JSON 파일에서 가져온 값)
    @SerializedName("itemId") val id: Long,
    @SerializedName("title") val title: String,
    @SerializedName("description") val description: String,
    @SerializedName("coverSmallUrl") val coverSmallUrl: String,
)
/*
{
    "title": "베스트셀러",
    "link": "http://book.interpark.com",
    "language": "ko",
    "copyright": "Copyright ⓒ 2009 INTERPARK INT All rights reserved.",
    "pubDate": "8 Jul 2021 22:30:02 GMT",
    "imageUrl": "http://bimage.interpark.com/renewPark/topGnb/logo.jpg",
    "totalResults": 30,
    "startIndex": 1,
    "itemsPerPage": 30,
    "maxResults": 30,
    "queryType": "",
    "searchCategoryId": "100",
    "searchCategoryName": "국내도서",
    "returnCode": "000",
    "returnMessage": "정상",
    "item": [   // JSONArray ja = new JSONArray(JSONObject); ja.length=12row
    {
        "itemId": 350339304,
        "title": "부의 시나리오",
        "description": "&#34인플레 공포 너머 다음 스텝을 준비하라! &#34금융천재 오건영의 똑똑한 투자 포트폴리오불안한 금융시장, 중심을 잡아줄 친절하고 생생한 인사이트\t★★★★ [삼프로TV] 누적 조회수 550만 회 ‘갓건영’으로 통하는 독보적 명강의\t\t★★★★ 경제전문가들이 인정하고 추천하는 금융전문가 1위!\t             \t★★★★ 수십만 독자가 열광한 베스트셀러 [부의 대이동] 후속작\t\t       오건영 저자가 불안한 금융시장 속, 흔들리는 투자자들의 다음 스텝을 지켜주기 위해 돌아왔다. 읽기만 해도 경제 흐름과 지식이 손에 잡히는 독보적인 오건영표 친절한 설명은 기본, 인플레 공포와 맞서 싸우는 것을 도와줄 ‘부의 시나리오’도 준비했다.‘여의도 1타강사’라는 수식어에 걸맞게 경제 개념이 머릿속에 쏙쏙 박히도록 그래프...",
        "pubDate": "20210607",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/9/3/0/4/350339304h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/9/3/0/4/350339304s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "페이지2",
        "customerReviewRank": 9.9,
        "author": "오건영",
        "translator": "",
        "isbn": "9791190977265",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=350339304&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=350339304&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=350339304&biz_cd=",
        "reviewCount": 2,
        "rank": 1
    },
    {
        "itemId": 350353111,
        "title": "완전한 행복",
        "description": "다시, 정유정!자기애의 늪에 빠진 삶은 얼마나 위태로운가,압도적 서사 위 정교하고 서늘한 공포  우리가 기다린 바로 그, 정유정!《내 인생의 스프링 캠프》 《내 심장을 쏴라》 《7년의 밤》 《28》 《종의 기원》 《진이, 지니》. 발표하는 작품마다 독자들의 열광적인 지지를 받으며 한국문학의 대체불가한 작가로 자리매김한 정유정이 신작 《완전한 행복》으로 돌아왔다. 500여 쪽을 꽉 채운 압도적인 서사와 적재적소를 타격하는 속도감 있는 문장, 치밀하고 정교하게 쌓아올린 플롯과 독자의 눈에 작열하는 생생한 묘사로 정유정만의 스타일을 가감 없이 보여주는 한편, 더 완숙해진 서스펜스와 인간의 심연에 대한 밀도 높은 질문으로 가득 찬 수작이다.  《완전한 행복》은 버스도 다니지 않는 버려진 시골집에서 늪에 사는 오리들...",
        "pubDate": "20210608",
        "priceStandard": 15800,
        "priceSales": 14220,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "790",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/3/1/1/1/350353111h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/3/1/1/1/350353111s.jpg",
        "categoryId": "101",
        "categoryName": "국내도서",
        "publisher": "은행나무",
        "customerReviewRank": 9.8,
        "author": "정유정",
        "translator": "",
        "isbn": "9791167370280",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=350353111&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=350353111&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=350353111&biz_cd=",
        "reviewCount": 6,
        "rank": 2
    },
    {
        "itemId": 350482767,
        "title": "조국의 시간",
        "description": "조국의 시간은 2019년 8월 9일, 조국이 법무부장관 후보로 지명된 이후 벌어진 일련의 사태를 정리하고 자신의 솔직한 심정을 기록했다. 진보적 지식인으로서 꿈꿔왔던 검찰개혁을 공직자로서 실현하는 과정에서 겪은 고난의 시간을 가감 없이 담아냈다.문재인 대통령과의 인연, 민정수석으로 청와대 입성 과정, 민정수석에서 법무부장관을 수락하는 과정까지 알려지지 않은 이야기가 가득하다. 출마냐 입각이냐를 두고 벌어지는 긴박한 상황과 최근까지 벌어지는 사건을 생생하게 다뤘다. 시민 한 분 한 분이 보내준 작은 응원이 만들어낸 큰 기적과 같은 이야기가 곳곳에 담겨 있다.    언론의 허위보도와 과장이 난무하고 검찰의 제 식구 감싸기로 일관한 조직 이기주의에 맞서 내놓는 최소한의 해명이자 역사적 기록이다. 진정한 정의는 무...",
        "pubDate": "20210531",
        "priceStandard": 17000,
        "priceSales": 15300,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "850",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/2/7/6/7/350482767h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/2/7/6/7/350482767s.jpg",
        "categoryId": "104",
        "categoryName": "국내도서",
        "publisher": "한길사",
        "customerReviewRank": 9.7,
        "author": "조국",
        "translator": "",
        "isbn": "9788935668663",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=350482767&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=350482767&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=350482767&biz_cd=",
        "reviewCount": 6,
        "rank": 3
    },
    {
        "itemId": 244844904,
        "title": "전쟁은 여자의 얼굴을 하지 않았다",
        "description": "전쟁에 직접 참전하고 살아남은 여성 200여 명의 목소리침묵을 강요당했던 그녀들의 눈물과 절규로 완성된전쟁문학의 기념비적인 걸작 2015년 노벨문학상을 수상한 벨라루스의 저널리스트이자 작가 스베틀라나 알렉시예비치의 [전쟁은 여자의 얼굴을 하지 않았다]가 문학동네에서 출간되었다. 스베틀라나 알렉시예비치는 소설가도, 시인도 아니다. 그러나 그는 자기만의 독특한 문학 장르를 창시했다. 일명 ‘목소리 소설(Novels of Voices)’, 작가 자신은 ‘소설-코러스’라고 부르는 장르이다. 다년간 수백 명의 사람들을 인터뷰해 모은 이야기를 Q&A가 아니라 일반 논픽션의 형식으로 쓰지만, 마치 소설처럼 읽히는 강렬한 매력이 있는 다큐멘터리 산문, 영혼이 느껴지는 산문으로 평가된다.  제2차세계대전 중에 백만 명이 넘...",
        "pubDate": "20151008",
        "priceStandard": 16000,
        "priceSales": 14400,
        "discountRate": "10",
        "saleStatus": "예약판매",
        "mileage": "800",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/4/9/0/4/244844904h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/4/9/0/4/244844904s.jpg",
        "categoryId": "102",
        "categoryName": "국내도서",
        "publisher": "문학동네",
        "customerReviewRank": 9.2,
        "author": "스베틀라나 알렉시예비치(Светлана Александровна Алексиевич)",
        "translator": "박은정",
        "isbn": "9788954637954",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=244844904&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=244844904&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=244844904&biz_cd=",
        "reviewCount": 40,
        "rank": 4
    },
    {
        "itemId": 348801388,
        "title": "그러라 그래",
        "description": "양희은 데뷔 51주년 현재진행형 에세이아이유, 이적, 김나영 추천!어떻게 인생이 쉽기만 할까?그저 좋아하는 걸 하고, 좋아하는 사람을 두고나답게 살면 그만이지 꽃다운 나이 칠십 세. 매일 아침 라디오 ‘여성시대’에서 청취자들과 친근한 대화를 나누는 친구 같은 라디오 DJ이자    등 수많은 히트곡을 낸 가수 양희은. 데뷔 51년 차에도 한 그루 느티나무처럼 늘 같은 자리에 서서 세월만큼 깊어진 목소리로 노래하는 현재진행형 가수 양희은의 에세이 《그러라 그래》가 출간되었다. 지나온 삶과 노래, 일상의 소중한 순간들을 마치 오랜 친구의 사연을 낭독하듯 따스하고 정감 있게 담았다. “그러라 그래”, “그럴 수 있어” 어떤 근심도 툭 털어버리는 양희은의 말처럼, 이 책에는 ‘쉽지 않은 인생을 정성껏 잘 살아보고 싶...",
        "pubDate": "20210412",
        "priceStandard": 14500,
        "priceSales": 13050,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "720",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/3/8/8/348801388h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/3/8/8/348801388s.jpg",
        "categoryId": "102",
        "categoryName": "국내도서",
        "publisher": "김영사",
        "customerReviewRank": 9.8,
        "author": "양희은",
        "translator": "",
        "isbn": "9788934984979",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=348801388&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=348801388&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=348801388&biz_cd=",
        "reviewCount": 41,
        "rank": 5
    },
    {
        "itemId": 349129937,
        "title": "미드나잇 라이브러리",
        "description": "밤 12시, 죽기 바로 전에만 열리는 마법의 도서관에서인생의 두 번째 기회를 드립니다★영국 아마존 종합 베스트셀러 1위★미국 아마존, [뉴욕타임스], [선데이타임스] 장기 베스트셀러★전 세계 42개국 번역 출간 계약!★ [어바웃 타임] 제작사 영화화 확정!&#34이 책들은 네가 살았을 수도 있는 모든 삶으로 들어가는 입구야.&#34더 이상 자신의 하찮고 지질한 삶을 견딜 수 없었던 주인공 노라 시드가 죽기로 결심한 것은 밤 11시 22분.  그가 눈을 뜬 곳은 삶과 죽음 사이의 미스터리한 공간 &#39미드나잇 라이브러리&#39. 시간은 자정에서 멈춰 있다. 도서관 사서 엘름 부인의 안내로 노라는 과거에 다른 선택을 했다면 살았을 수도 있는 또 다른 삶을 살아보며, 가장 완벽한 삶을 찾는 모험을 시작한다. &#34강렬한 존재감과 위대한...",
        "pubDate": "20210428",
        "priceStandard": 15800,
        "priceSales": 14220,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "790",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/9/9/3/7/349129937h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/9/9/3/7/349129937s.jpg",
        "categoryId": "101",
        "categoryName": "국내도서",
        "publisher": "인플루엔셜",
        "customerReviewRank": 9.7,
        "author": "매트 헤이그(Matt Haig)",
        "translator": "노진선",
        "isbn": "9791191056556",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=349129937&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=349129937&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=349129937&biz_cd=",
        "reviewCount": 12,
        "rank": 6
    },
    {
        "itemId": 349804863,
        "title": "매매의 기술",
        "description": " 주식은 타이밍이다!여의도 최고의 트레이더와 함께하는 승률 99%의16가지 상황별 매매 타이밍과 실전 노하우매매를 하다 보면 매 순간 선택의 갈림길에 놓인다. 이유는 모르지만 갑자기 매수세가 강해지며 주가가 치솟는 종목이 있는데, 이럴 때 동반 매수해야 하는지 아니면 위험 신호이니 보유 중인 주식을 팔아야 하는지 고민이 된다. 그 반대도 마찬가지다. 갑자기 매도세가 강해지며 낙폭을 키워가는 종목에서는, 보유 중인 주식을 팔아야 하는지 아니면 물량을 끌어내려는 매집 세력의 제스처일 뿐이니 나도 덩달아 수량을 늘려야 하는지 고민하게 된다. 특정 가격에 매수 호가 또는 매도 호가가 이례적으로 쌓여 있을 때도 그것이 어떤 의미인지 속 시원하게 알고 싶어진다. 시장에 참여하다 보면 이런 일은 부지기수다. 여의도 최고...",
        "pubDate": "20210514",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/4/8/6/3/349804863h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/4/8/6/3/349804863s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "포레스트북스",
        "customerReviewRank": 8.9,
        "author": "박병창",
        "translator": "",
        "isbn": "9791191347180",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=349804863&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=349804863&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=349804863&biz_cd=",
        "reviewCount": 4,
        "rank": 7
    },
    {
        "itemId": 298189479,
        "title": "해커스 토익 기출 보카 TOEIC VOCA 영단어",
        "description": "토익 베스트셀러 1위주제별 연상암기로 토익 영단어 30일 완성 [이런 분에게 추천합니다]1. 토익 기출 보카와 최신 출제포인트를 빠르게 정리하고 싶은 분들2. 내 목표 점수에 맞춰 토익 단어를 학습하고 싶은 분들3. 다양한 학습 장치로 단어를 쉽게 외우고 오래 기억하고 싶은 분들 [해커스 교재만의 특장점]1. 토익 최신 기출 단어 단기 정복 1) 토익 최신 기출 단어, 필수 어휘 30일 완성 2) 토익 기초 단어부터 고난도 어휘까지 모든 난이도의 단어 수록 3) 개별학습 및 스터디 학습에 활용 가능한 맞춤형 학습방법 제공2. 주제별 연상암기로 쉽고 재미있게 외우는 단어 1) 토익 빈출 주제 30개에 맞춰 단어를 수록하여 주제별로 묶어서 쉽게 암기 2) 삽화 및 스토리와 함께 재미있게 단어 학습 3) 단어 M...",
        "pubDate": "20200305",
        "priceStandard": 12900,
        "priceSales": 11610,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "640",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/9/4/7/9/298189479h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/9/4/7/9/298189479s.jpg",
        "categoryName": "",
        "publisher": "해커스어학연구소",
        "customerReviewRank": 9.2,
        "author": "데이비드 조(David Cho)",
        "translator": "",
        "isbn": "9788965422785",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=298189479&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=298189479&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=298189479&biz_cd=",
        "reviewCount": 8,
        "rank": 8
    },
    {
        "itemId": 351951596,
        "title": "흔한남매 8",
        "description": "더위를 날리는 흔한남매의 오싹하고 깜찍한 일상!흔한남매의 일상 탐구, 으뜸이 방에서 펼쳐진 무서운 이야기, 엄지와의 첫 만남, 흔한 동네의 흔한 귀신, 한여름 밤의 공포 영화, 집에서 노는 꿀팁, 서프라이즈 생일 파티 등 오싹하고 웃음 가득한 일상 속으로 떠나 볼까요?유튜브 218만 구독 돌파! 인기 크리에이터 흔한남매&#39흔한남매&#39는 유튜브 구독자 수가 218만 명, 누적 조회 수가 19억 회를 넘어서는 인기 크리에이터로, 흔한컴퍼니에 소속되어 있습니다. 상황극 콩트 등을 통해 어린이들에게 큰 사랑을 받고 있으며, 주로 남매 사이에서 일어날 수 있는 현실적인 에피소드를 코믹하게 그려 내어 웃음과 공감을 이끌어 내고 있습니다.흔한남매가 선사하는 유쾌한 우애와 순수한 웃음!《흔한남매 8》은 &#39흔한남매&#39 유튜브 영...",
        "pubDate": "20210714",
        "priceStandard": 13500,
        "priceSales": 12150,
        "discountRate": "10",
        "saleStatus": "예약판매",
        "mileage": "670",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/5/9/6/351951596h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/5/9/6/351951596s.jpg",
        "categoryId": "110",
        "categoryName": "국내도서",
        "publisher": "미래엔아이세움",
        "customerReviewRank": 0,
        "author": "백난도",
        "translator": "",
        "isbn": "9791164138197",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=351951596&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=351951596&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=351951596&biz_cd=",
        "reviewCount": 0,
        "rank": 9
    },
    {
        "itemId": 351732842,
        "title": "설민석의 한국사 대모험 17",
        "description": "황금순 할머니의 소원을 이루기 위한 설쌤과 온달, 평강의슬프지만 아름다운 역사 여행이 시작됩니다!크리스마스의 기적부터 임시수도 부산, 학도병까지,한국 근현대사의 가장 큰 비극, 6.25 전쟁이 낳은 아픔을 돌아봅니다.2021년 6월 25일은 6.25 전쟁이 발발한 지 71년이 되는 해입니다. 당시에 태어난 분들이 이제 70세가 넘어 인자한 할아버지, 할머니가 되셨을 만큼의 시간이 흘렀습니다. 그러나 여전히 한반도는 분단국가이고, 아직도 수많은 이산가족이 슬픔을 겪고 있으며, 전쟁에 참여한 부모, 형제들의 생사 여부도 모른 채, 만약 죽었다면 유해라도 돌아오기를 간절한 마음으로 기다리고 있습니다. 『설민석의 한국사 대모험 17』은 우리 현대사의 가장 큰 비극인 6.25 전쟁을 다루고 있습니다. 정치적, 군사적...",
        "pubDate": "20210721",
        "priceStandard": 12000,
        "priceSales": 10800,
        "discountRate": "10",
        "saleStatus": "예약판매",
        "mileage": "600",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/2/8/4/2/351732842h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/2/8/4/2/351732842s.jpg",
        "categoryId": "110",
        "categoryName": "국내도서",
        "publisher": "아이휴먼",
        "customerReviewRank": 0,
        "author": "설민석,스토리박스",
        "translator": "",
        "isbn": "9791165382940",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=351732842&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=351732842&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=351732842&biz_cd=",
        "reviewCount": 0,
        "rank": 10
    },
    {
        "itemId": 334240809,
        "title": "달러구트 꿈 백화점",
        "description": "잠들어야만 입장 가능한 꿈 백화점에서 일어나는 비밀스럽고도 기묘하며 가슴 뭉클한 판타지 소설 여기는 잠들어야만 입장할 수 있는 &#39달러구트 꿈 백화점&#39입니다. 잠들어야만 입장할 수 있는 독특한 마을. 그곳에 들어온 잠든 손님들에게 가장 인기 있는 곳은, 온갖 꿈을 한데 모아 판매하는 &#39달러구트의 꿈 백화점&#39이다. 긴 잠을 자는 사람들은 물론이고, 짧은 낮잠을 자는 사람들과 동물들로 매일매일 대성황을 이룬다. 범상치 않은 혈통의 주인장 &#39달러구트&#39, 그리고 그의 최측근에서 일하게 된 신참 직원 &#39페니&#39, 꿈을 만드는 제작자 &#39아가넵 코코&#39, 그리고 베일에 둘러싸인 비고 마이어스...등이 등장한다. [달러구트 꿈 백화점]은 &#39무의식에서만 존재하는 꿈을 정말 사고 팔 수 있을까?&#39라는 기발한 질문에 답을 찾아가며,...",
        "pubDate": "20200708",
        "priceStandard": 13800,
        "priceSales": 12420,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "690",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/0/8/0/9/334240809h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/0/8/0/9/334240809s.jpg",
        "categoryId": "101",
        "categoryName": "국내도서",
        "publisher": "팩토리나인",
        "customerReviewRank": 9.8,
        "author": "이미예",
        "translator": "",
        "isbn": "9791165341909",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=334240809&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=334240809&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=334240809&biz_cd=",
        "reviewCount": 30,
        "rank": 11
    },
    {
        "itemId": 352090652,
        "title": "이상한 과자 가게 전천당 11",
        "description": "국내 누적 90만 부 돌파!누구나 공감하는 고민과 불안을 때론 통쾌하게 날려주고, 때론 따뜻하게 위로하는재미와 감동의 판타지 동화. [이상한 과자 가게 전천당] 시리즈의 열한 번째 이야기. 전천당vs.화앙당의 최종 결전끈질긴 악연을 끊어낼 날이 다가왔다!과연 냉혹한 싸움 끝에 누가 웃을 것인가?전천당의 냉동고에 갇혀 있던 요도미가 몰래 빠져나와 베니코를 괴롭힐 수작을 부린다. 바로 손님들에게 전천당 과자보다 더 강력한 과자를 선택하게 하는 것. 공부를 잘하고 싶은 학생에게  대신 를, 벌레가 너무 싫은 여성에게  대신  등을 건네며 전천당 과자를 버리게끔 만든다. 그러자 전천당의 마네키네코들에게 끔찍한 일이 벌어지는데…. 더 이상 참을 수 없는 베니코는 서늘한 미소를 지으며 요도미를 찾으러 나선다. 베니코는...",
        "pubDate": "20210712",
        "priceStandard": 12000,
        "priceSales": 10800,
        "discountRate": "10",
        "saleStatus": "예약판매",
        "mileage": "600",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/0/6/5/2/352090652h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/0/6/5/2/352090652s.jpg",
        "categoryId": "110",
        "categoryName": "국내도서",
        "publisher": "길벗스쿨",
        "customerReviewRank": 0,
        "author": "히로시마 레이코",
        "translator": "김정화",
        "isbn": "9791164063734",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=352090652&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=352090652&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=352090652&biz_cd=",
        "reviewCount": 0,
        "rank": 12
    },
    {
        "itemId": 340003129,
        "title": "어떻게 말해줘야 할까",
        "description": "채널A  SBS 국민 육아멘토 오은영 박사가 알려주는 ‘부모의 말’육아 현실을 200퍼센트 반영한 130가지 한마디‘국민 육아멘토’ ‘대한민국 엄마·아빠들의 엄마’ 오은영 박사의 신간. 쉽게 따라 할 수 있는 ‘부모의 말’을 친절하게 소개하는 육아서이다. 오은영 박사가 이전에 낸 책들과 비교하면 크기는 작고 내용은 쉽다. 그렇다고 내용이 부실하진 않다. 육아 현실에 즉각 활용할 수 있는 현실밀착형 말 130가지를 빼곡히 담았다. 동화책 《꽝 없는 뽑기 기계》(비룡소문학상 수상작)의 그림작가 차상미의 그림을 여럿 넣어 따스하면서 친근한 분위기도 더했다.당장 외출해야 하는데 다른 옷을 입겠다며 떼쓰는 아이, 남의 집 물건을 함부로 만지는 아이, 친구 혹은 남매와 자주 다투는 아이, 심하게 고집부리는 아이, 감정...",
        "pubDate": "20201022",
        "priceStandard": 17500,
        "priceSales": 15750,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "870",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/3/1/2/9/340003129h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/3/1/2/9/340003129s.jpg",
        "categoryId": "111",
        "categoryName": "국내도서",
        "publisher": "김영사",
        "customerReviewRank": 9.9,
        "author": "오은영",
        "translator": "",
        "isbn": "9788934986652",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=340003129&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=340003129&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=340003129&biz_cd=",
        "reviewCount": 11,
        "rank": 13
    },
    {
        "itemId": 341968239,
        "title": "공정하다는 착각",
        "description": "마이클 샌델 10여 년 만의 신간, 《공정하다는 착각》 출간!샌델, 기울어진 사회구조 이면에 도사린 ‘능력주의의 덫’을 해체하다또 다시 ‘공정’이 화두다. 언론 미디어를 통해, 부유층과 빈곤층, 청년과 장년, 정치인의 입을 통해 끊임없이 쏟아져 나온다. 기업은 정규직&#8228;비정규직 논란에서 비롯된 ‘공정 채용’ 문제로 혼란에 빠져 있고, 정치권에선 ‘공정경제3법’과 ‘재난지원금’ 등에 대한 각기 다른 해석으로 떠들썩하다. 대통령은 “하나의 공정이 또 다른 불공정을 부르는 상황”을 언급하며 어려움을 토로하기도 했다.이렇듯 ‘공정’이라는 하나의 화두를 두고 각계각층이 충돌하고 있는 상황에서, 마이클 샌델 하버드대 교수가 《돈으로 살 수 없는 것들》 이후 8년 만에 쓴 신간 《공정하다는 착각》이 출간되었다....",
        "pubDate": "20201201",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/8/2/3/9/341968239h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/8/2/3/9/341968239s.jpg",
        "categoryId": "104",
        "categoryName": "국내도서",
        "publisher": "와이즈베리",
        "customerReviewRank": 9.7,
        "author": "마이클 샌델(Michael J. Sandel)",
        "translator": "함규진",
        "isbn": "9791164136452",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=341968239&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=341968239&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=341968239&biz_cd=",
        "reviewCount": 26,
        "rank": 14
    },
    {
        "itemId": 349301001,
        "title": "소크라테스 익스프레스",
        "description": "“인생에서 길을 잃는 수많은 순간마다&#160;이 철학자들의 목소리가 들려올 것이다” 베스트셀러 작가 에릭 와이너와 함께 떠나는 철학자행 특급 열차! 2020 아마존 베스트 논픽션, 2020 NPR 올해의 책- 소크라테스처럼 궁금해하고, 루소처럼 걷고, 소로처럼 볼 수 있을까?- 간디는 어떻게 싸웠을까, 에픽테토스가 역경에서 벗어난 방법은 무엇일까?- 노화와 죽음에 대해 보부아르와 몽테뉴는 뭐라고 했을까?- 에피쿠로스처럼 즐기고, 에픽테토스처럼 역경에 대처할 수 있을까?프랑스 사상가 모리스 리즐링은 말한다. “결국 인생은 우리 모두를 철학자로 만든다.” 하지만 인생이 호락호락하지 않음을 우리는 수시로 깨닫는다. 여기, 인생에서 가장 중요한 질문을 하고 답을 찾기 위해 평생을 바친 철학자들이 있다. 그들에게 ...",
        "pubDate": "20210428",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/0/0/1/349301001h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/0/0/1/349301001s.jpg",
        "categoryId": "119",
        "categoryName": "국내도서",
        "publisher": "어크로스",
        "customerReviewRank": 9.7,
        "author": "에릭 와이너(Eric Weiner)",
        "translator": "김하현",
        "isbn": "9791190030922",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=349301001&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=349301001&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=349301001&biz_cd=",
        "reviewCount": 4,
        "rank": 15
    },
    {
        "itemId": 342296805,
        "title": "어린이라는 세계",
        "description": "어린이에 대해 생각할수록 우리의 세계는 넓어진다 어린이는 잘 보이지 않는다. 몸이 작아서이기도 하고, 목소리가 작아서이기도 하다. 양육이나 교육, 돌봄을 맡고 있는 사람이 아니라면 우리 곁에 어린이가 ‘있다’는 사실을 의식하지 못한 채 살아가기 쉽다. 10년 남짓 어린이책 편집자로 일했고, 지금은 독서교실에서 어린이들과 책을 읽는 김소영은 어린이의 존재를 더 잘 보이게 하기 위해 부지런히 글을 쓰고 목소리를 내 왔다. 이 책에는 김소영이 어린이들과 만나며 발견한, 작고 약한 존재들이 분주하게 배우고 익히며 자라나는 세계가 담겨 있다. 이 세계의 어린이는 우리 곁의 어린이이기도 하고, 우리 모두가 통과해온 어린이이기도 하며, 동료 시민이자 다음 세대를 이루는 어린이이기도 하다. 독서교실 안팎에서 어린이들 특유...",
        "pubDate": "20201116",
        "priceStandard": 15000,
        "priceSales": 13500,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "750",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/8/0/5/342296805h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/8/0/5/342296805s.jpg",
        "categoryId": "102",
        "categoryName": "국내도서",
        "publisher": "사계절",
        "customerReviewRank": 9.8,
        "author": "김소영",
        "translator": "",
        "isbn": "9791160946918",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=342296805&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=342296805&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=342296805&biz_cd=",
        "reviewCount": 7,
        "rank": 16
    },
    {
        "itemId": 351769254,
        "title": "추미애의 깃발",
        "description": "정의로운 세상을 향한 희망의 깃발을 높이 들다!",
        "pubDate": "20210701",
        "priceStandard": 17000,
        "priceSales": 15300,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "850",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/9/2/5/4/351769254h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/9/2/5/4/351769254s.jpg",
        "categoryId": "104",
        "categoryName": "국내도서",
        "publisher": "한길사",
        "customerReviewRank": 0,
        "author": "추미애,김민웅",
        "translator": "",
        "isbn": "9788935668687",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=351769254&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=351769254&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=351769254&biz_cd=",
        "reviewCount": 0,
        "rank": 17
    },
    {
        "itemId": 346581711,
        "title": "[심화] 2021 큰별쌤 최태성의 별별한국사 한국사능력검정시험 상 - 1,2,3급",
        "description": "오랜 연구와 검증으로 한국사에 기초가 전혀 없는 사람도 단기간에 한능검에 합격할 수 있는 최적의 구성을 완성하였습니다. 판서의 장인 큰별쌤 최태성이 핵심만을 모아 만든 아트 판서를 수록하고, 시험에 자주 등장하는 사료, 사진, 지도 등을 모아 해설하여 합격을 위한 필수 개념을 익히기 쉽게 하였습니다. 또한, 한능검 기출문제를 모두 분석한 후, 기출 선택지를 이용한 별 채우기 문제를 수록하여 자연스럽게 기출 선택지가 기억될 수 있도록 하였고, 반복적으로 출제되는 주제의 최신 기출문제를 꼼꼼하고 친절한 해설과 함께 담아 실전에 대비할 수 있도록 하였습니다. 여기에 한국사 연표와 지역의 역사를 담은 지도를 통해 한국사 흐름잡기가 더욱 쉬울 것입니다.제시된 이미지는 책의 뒷표지입니다.많은 사람들이 쓰는 책의 앞표지...",
        "pubDate": "20210201",
        "priceStandard": 15000,
        "priceSales": 13500,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "750",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/7/1/1/346581711h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/7/1/1/346581711s.jpg",
        "categoryId": "123",
        "categoryName": "국내도서",
        "publisher": "이투스북",
        "customerReviewRank": 0,
        "author": "최태성",
        "translator": "",
        "isbn": "9791165985110",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=346581711&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=346581711&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=346581711&biz_cd=",
        "reviewCount": 0,
        "rank": 18
    },
    {
        "itemId": 351069543,
        "title": "돈의 역사는 되풀이된다",
        "description": "돈의 주도권을 잡으려면 돈의 흐름을 읽어야 한다!돈 공부만 28년, 국내 최고의 이코노미스트! 홍춘욱 박사가 들려주는 ‘현실’ 경제수업과 최고의 투자법이 책은 국내 최고의 이코노미스트 홍춘욱 박사가 돈 공부만 28년 한 모든 노하우를 담아 경제 흐름과 부동산, 주식, 투자에 필요한 현실적인 조언, 즉 돈의 흐름을 읽는 법을 담았다. 돈의 주도권을 잡기 위해서 우리는 반드시 돈의 흐름을 읽는 법을 알아야 한다. 홍춘욱 박사는 아들에게 물려줄 부의 유산으로 ‘돈의 흐름을 읽는 법’을 꼽았고, 홍 박사가 가진 돈에 관한 인사이트를 집대성해 불확실한 시대에 나를 지키는 현실적인 투자 방법을 알려주고 있다. 은행과 증권사의 이코노미스트로, 국민연금공단의 투자 운용 매니저로, 경제·경영학자로 탄탄히 쌓아 올린 저자의 ...",
        "pubDate": "20210616",
        "priceStandard": 16000,
        "priceSales": 14400,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "800",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/9/5/4/3/351069543h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/9/5/4/3/351069543s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "포르체",
        "customerReviewRank": 9.9,
        "author": "홍춘욱",
        "translator": "",
        "isbn": "9791191393163",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=351069543&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=351069543&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=351069543&biz_cd=",
        "reviewCount": 1,
        "rank": 19
    },
    {
        "itemId": 340382779,
        "title": "2030 축의 전환",
        "description": "변화는 코로나19에서 끝나지 않는다!2030년, 세계는 더 심오하고 거대한 질적 전환을 맞이한다!세계적인 경영 석학 마우로 기옌 와튼스쿨 교수,경제학, 지정학, 사회학을 넘나드는 파격적 통찰로 전 세계 리더들을 충격에 빠뜨리다!4차 산업혁명 다음 혁명은 어느 나라가 주도할까? 출생률 감소와 인구 고령화는 코로나19와 맞물려 어떤 양상으로 진행될까? 디지털 시대에 태어난 밀레니얼 세대와 세계에서 가장 큰 소비자 집단인 실버 세대 사이에는 어떤 기회가 숨겨져 있을까? 규모와 수가 빠르게 늘고 있는 도시들은 기후변화와 양극화를 어떻게 극복할 수 있을까? [2030 축의 전환: 새로운 부와 힘을 탄생시킬 8가지 거대한 물결]은 현재 진행 중인 주요 추세들이 ‘2030년’에 수렴하면, 지금과는 완전히 다른 세상이 펼...",
        "pubDate": "20201016",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/2/7/7/9/340382779h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/2/7/7/9/340382779s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "리더스북",
        "customerReviewRank": 9.7,
        "author": "마우로 기옌(Mauro F. Guillen)",
        "translator": "우진하",
        "isbn": "9788901246086",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=340382779&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=340382779&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=340382779&biz_cd=",
        "reviewCount": 20,
        "rank": 20
    },
    {
        "itemId": 350356636,
        "title": "강원국의 어른답게 말합니다  ",
        "description": "&#34말은 어떻게 삶이 되는가?&#34존중하고 존중받는 일상을 빚어내는 힘진짜 어른다움의 완성은 말 속에 있다★ 50만 독자가 선택한 베스트셀러 작가 강원국 신작★ 전직 대통령 연설비서관의 말하기 특강★ KBS 1라디오 [강원국의 말 같은 말] 공식 출간 도서수많은 독자에게 사랑받은 베스트셀러 [대통령의 글쓰기]의 저자 강원국이 삶의 품격을 높이는 말하기에 관해 이야기한다. 대기업 회장과 두 전 대통령의 ‘말’을 듣고 쓰고 고치는 일을 해온 그는 어떻게 하면 가장 쉬운 말로 진심을 전할 수 있는지 오랫동안 고민했다. 이 책은 누구보다 ‘말의 기본’에 천착해온 저자가 ‘말이 되는 삶, 삶이 되는 말’에 관해 들려주는 73가지 말공부 수업을 담았다. 세상에는 말이 칼이 된다는 것을, 그 칼이 자신을 향한다는 것을 잊은 ...",
        "pubDate": "20210526",
        "priceStandard": 16000,
        "priceSales": 14400,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "800",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/6/3/6/350356636h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/6/3/6/350356636s.jpg",
        "categoryId": "118",
        "categoryName": "국내도서",
        "publisher": "웅진지식하우스",
        "customerReviewRank": 10,
        "author": "강원국",
        "translator": "",
        "isbn": "9788901250014",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=350356636&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=350356636&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=350356636&biz_cd=",
        "reviewCount": 2,
        "rank": 21
    },
    {
        "itemId": 350096128,
        "title": "smart (スマ-ト) - 2021년 8월호 (부록 : A BATHING APE 드라이백)",
        "description": "",
        "pubDate": "20210625",
        "priceStandard": 10720,
        "priceSales": 10720,
        "discountRate": "0",
        "saleStatus": "판매중",
        "mileage": "540",
        "mileageRate": "5",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/1/2/8/350096128h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/1/2/8/350096128s.jpg",
        "categoryId": "214",
        "categoryName": "국내도서",
        "publisher": "寶島社(보도사)",
        "customerReviewRank": 0,
        "author": "",
        "translator": "",
        "isbn": "4910155210819",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=350096128&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=350096128&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=350096128&biz_cd=",
        "reviewCount": 0,
        "rank": 22
    },
    {
        "itemId": 322696521,
        "title": "ETS 토익 정기시험 기출문제집 1000 Vol.2 READING(리딩)",
        "description": "YBM은 토익 출제기관 ETS와 한국 독점 계약사로, 토익 기출문제는 YBM이 독점 출간합니다.",
        "pubDate": "20191216",
        "priceStandard": 17800,
        "priceSales": 16020,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "890",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/5/2/1/322696521h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/5/2/1/322696521s.jpg",
        "categoryName": "",
        "publisher": "YBM(와이비엠)",
        "customerReviewRank": 10,
        "author": "ETS(Educational Testing Service)",
        "translator": "",
        "isbn": "9788917232196",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=322696521&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=322696521&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=322696521&biz_cd=",
        "reviewCount": 2,
        "rank": 23
    },
    {
        "itemId": 346581786,
        "title": "[심화] 2021 큰별쌤 최태성의 별별한국사 한국사능력검정시험 하 - 1,2,3급",
        "description": "오랜 연구와 검증으로 한국사에 기초가 전혀 없는 사람도 단기간에 한능검에 합격할 수 있는 최적의 구성을 완성하였습니다. 판서의 장인 큰별쌤 최태성이 핵심만을 모아 만든 아트 판서를 수록하고, 시험에 자주 등장하는 사료, 사진, 지도 등을 모아 해설하여 합격을 위한 필수 개념을 익히기 쉽게 하였습니다. 또한, 한능검 기출문제를 모두 분석한 후, 기출 선택지를 이용한 별 채우기 문제를 수록하여 자연스럽게 기출 선택지가 기억될 수 있도록 하였고, 반복적으로 출제되는 주제의 최신 기출문제를 꼼꼼하고 친절한 해설과 함께 담아 실전에 대비할 수 있도록 하였습니다. 여기에 한국사 연표와 지역의 역사를 담은 지도를 통해 한국사 흐름잡기가 더욱 쉬울 것입니다.제시된 이미지는 책의 뒷표지입니다.많은 사람들이 쓰는 책의 앞표지...",
        "pubDate": "20210201",
        "priceStandard": 14000,
        "priceSales": 12600,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "700",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/7/8/6/346581786h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/7/8/6/346581786s.jpg",
        "categoryId": "123",
        "categoryName": "국내도서",
        "publisher": "이투스북",
        "customerReviewRank": 0,
        "author": "최태성",
        "translator": "",
        "isbn": "9791165985127",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=346581786&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=346581786&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=346581786&biz_cd=",
        "reviewCount": 0,
        "rank": 24
    },
    {
        "itemId": 322696313,
        "title": "ETS 토익 정기시험 기출문제집 1000 Vol.2 LISTENING(리스닝)",
        "description": "YBM은 토익 출제기관 ETS와 한국 독점 계약사로, 토익 기출문제는 YBM이 독점 출간합니다.",
        "pubDate": "20191216",
        "priceStandard": 17800,
        "priceSales": 16020,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "890",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/3/1/3/322696313h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/3/1/3/322696313s.jpg",
        "categoryName": "",
        "publisher": "YBM(와이비엠)",
        "customerReviewRank": 9.9,
        "author": "ETS(Educational Testing Service)",
        "translator": "",
        "isbn": "9788917232189",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=322696313&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=322696313&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=322696313&biz_cd=",
        "reviewCount": 4,
        "rank": 25
    },
    {
        "itemId": 213290111,
        "title": "밤의 여행자들",
        "description": "오늘의 젊은 작가 03  문학성 다양성 참신성 한국문학의 미래를 이끌어 갈 신예들이 펼쳐 가는 경장편 시리즈&#34어느 오후의 거대한 쓰나미 아래서, 그곳의 모든 생활들이 갑자기 점. 점. 점. 으로 끊어졌다.&#34한겨레문학상, 이효석문학상 수상 작가 윤고은이 펼치는 전혀 새로운 상상력&#39재난 여행&#39 상품 수석 프로그래머 &#39고요나&#39의기상천외하고 스펙터클한 재난 사용법  윤고은이 마지막으로 남겨 두고 싶었던 유토피아와 결별하는 소설적 공간이며 지독한 현실의 중압감을 다른 방식으로 허구화한 첫 작품이자 자신의 어떠한 문학적 기록을 거절하는 첫걸음. 단언컨대 [밤의 여행자들]은 윤고은의 소설적 세계의 전회이자 또 다른 도약임에 틀림없다. 아마도 우리는 [밤의 여행자들] 이후 달라진 윤고은을 만나게 될 것이다. ―강유정(문학...",
        "pubDate": "20131011",
        "priceStandard": 13000,
        "priceSales": 11700,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "650",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/0/1/1/1/213290111h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/0/1/1/1/213290111s.jpg",
        "categoryId": "101",
        "categoryName": "국내도서",
        "publisher": "민음사",
        "customerReviewRank": 9.4,
        "author": "윤고은",
        "translator": "",
        "isbn": "9788937473036",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=213290111&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=213290111&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=213290111&biz_cd=",
        "reviewCount": 27,
        "rank": 26
    },
    {
        "itemId": 333676024,
        "title": "기분이 태도가 되지 않게 (썸머 에디션)",
        "description": "집에서, 회사에서, 인간관계에서  후회가 사라지고 오해가 줄어드는 기분 사용법사무실의 분위기를 크게 좌우하는 한 사람이 있다. 출근하면서부터 ‘나 오늘 건드리면 가만 안 둬…’ 경고를 온몸으로 뿜어낸다. 다른 직원들은 슬금슬금 눈치를 보고, 이 사람의 오늘 기분에 따라 사무실은 온탕과 냉탕을 오간다. 왜 자기 선에서 감정을 추스르지 못하고 안 좋은 기분으로 남에게 민폐를 끼치는 걸까? 하지만 그 사람의 마음도 편치는 않다. 이러면 안 된다는 걸 알면서도 밖으로 드러나는 감정을 참을 도리가 없다. 프로다운 모습을 보여야 할 일터에서도 감정 기복을 그대로 보여주면 스스로 손해를 볼 뿐이다. 회사에서뿐만 아니라, 우리는 가족에게나 친구에게 안 좋은 기분을 티 내며 소중한 사람을 질리게 만들어버리고 후회하기도 한다...",
        "pubDate": "20200630",
        "priceStandard": 14000,
        "priceSales": 12600,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "700",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/6/0/2/4/333676024h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/6/0/2/4/333676024s.jpg",
        "categoryId": "118",
        "categoryName": "국내도서",
        "publisher": "갤리온",
        "customerReviewRank": 9.8,
        "author": "레몬심리",
        "translator": "박영란",
        "isbn": "9788901243658",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=333676024&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=333676024&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=333676024&biz_cd=",
        "reviewCount": 17,
        "rank": 27
    },
    {
        "itemId": 345414357,
        "title": "주린이가 가장 알고 싶은 최다질문 TOP 77",
        "description": "‘염블리’ 염승환이 전하는 주식투자 시 필수지식과 태도, 경험을 담은 주식투자 바이블!2020년 100조 원이 넘는 주린이들의 자금이 주식시장에 유입되었다. 세대를 막론하고 주식투자가 건전한 재테크 및 노후준비 수단으로 부상하며 많은 이들이 주식투자 정보 방송을 즐겨보고 듣기 시작했다. 주린이들의 사랑을 받으며 주목받는 스타도 생겨났다. 이 책의 저자인 염승환이 바로 그 대표주자다. 매일 아침 유튜브 방송 에 출연하며 주식시황 및 투자정보를 친절하고 성실하게 전달하는 그에게 많은 주린이들이 신뢰와 감사 메시지를 보냈다. 저자도 주린이 시절, 막연한 느낌과 소문에 의지해 주식투자를 하던 때가 있었다. 요행히 큰 수익률을 올리기도 했지만 보유하고 있던 주식이 상장폐지 되면서 큰 손실과 상처를 입은 뼈아픈 경험이...",
        "pubDate": "20210120",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/4/3/5/7/345414357h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/4/3/5/7/345414357s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "메이트북스",
        "customerReviewRank": 9.8,
        "author": "염승환",
        "translator": "",
        "isbn": "9791160023176",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=345414357&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=345414357&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=345414357&biz_cd=",
        "reviewCount": 15,
        "rank": 28
    },
    {
        "itemId": 322941058,
        "title": "해커스 토익 RC READING 리딩 (최신개정판)",
        "description": "14년 연속 베스트셀러 1위토익 리딩의 기본서! 문법/독해/어휘에서 실전까지! 1. 토익 시험 최신기출경향 완벽 분석 및 반영2. &#39토익 READING 최신 출제 경향 한눈에 보기&#39 제공3. 한 권으로 기본부터 실전까지 토익 RC 완벽 대비4. 해커스 스타강사의 무료 실전 문제 해설강의 제공5. 진단고사로 실력 점검하고 자신에게 맞는 수준별 학습플랜 선택",
        "pubDate": "20200302",
        "priceStandard": 18800,
        "priceSales": 16920,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "940",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/1/0/5/8/322941058h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/1/0/5/8/322941058s.jpg",
        "categoryName": "",
        "publisher": "해커스어학연구소",
        "customerReviewRank": 9.9,
        "author": "데이비드 조(David Cho)",
        "translator": "",
        "isbn": "9788965423348",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=322941058&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=322941058&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=322941058&biz_cd=",
        "reviewCount": 6,
        "rank": 29
    },
    {
        "itemId": 346952540,
        "title": "부자들은 이런 주식을 삽니다",
        "description": "〈유 퀴즈 온 더 블럭〉 〈정산회담〉으로 얼굴을 알린 젊은 부자 김현준 대표의 주식투자서. 861%라는 놀라운 수익률을 자랑하는 김현준 대표는 주식시장에서 승자가 되기 위해서는 부자의 시선으로 시장을 바라봐야 한다고 말한다. 우리나라 주식시장에서 돈을 잃는 투자자는 전부 ‘주린이’다. 대박을 꿈꾸며 급등장에 들어왔지만 수익을 못 내고 있거나, 작은 이익에 흔들려 자주 매매하거나 시장은 보지 않고 그냥 무작정 우량주에 투자하는 사람이 전부 여기에 해당한다. 《부자들은 이런 주식을 삽니다》는 이러한 투자 관성을 버리고, 어떠한 상황에서도 잃지 않는 투자를 할 수 있는 비법을 ‘부자의 시선’으로 ‘부자의 마인드’로 말해주는 책이다.",
        "pubDate": "20210225",
        "priceStandard": 18000,
        "priceSales": 16200,
        "discountRate": "10",
        "saleStatus": "판매중",
        "mileage": "900",
        "mileageRate": "6",
        "coverSmallUrl": "http://bimage.interpark.com/goods_image/2/5/4/0/346952540h.jpg",
        "coverLargeUrl": "http://bimage.interpark.com/goods_image/2/5/4/0/346952540s.jpg",
        "categoryId": "117",
        "categoryName": "국내도서",
        "publisher": "위즈덤하우스",
        "customerReviewRank": 9,
        "author": "김현준",
        "translator": "",
        "isbn": "9791191425604",
        "link": "http://book.interpark.com/blog/integration/product/itemDetail.rdo?prdNo=346952540&refererType=8305",
        "mobileLink": "http://m.book.interpark.com/view.html?PRD_NO=346952540&SHOP_NO=0000400000",
        "additionalLink": "http://book.interpark.com/gate/ippgw.jsp?goods_no=346952540&biz_cd=",
        "reviewCount": 1,
        "rank": 30
    }
    ]
}
*/